tap 'homebrew/cask-versions'

cask '1password'
cask 'activitywatch'
# cask 'alt-tab'  # old app switcher
cask 'android-platform-tools'
cask 'bartender'
# cask 'brave-browser'
cask 'coconutbattery'
cask 'contexts'  # app switcher
cask 'daisydisk'
cask 'db-browser-for-sqlite'
cask 'dbeaver-community'
cask 'discord'
cask 'docker'
cask 'gyroflow'
cask 'jupyter-notebook-viewer'
cask 'losslesscut'
cask 'maccy'
cask 'menumeters'
# cask 'microsoft-edge'
# cask 'microsoft-teams'
cask 'namechanger'
cask 'qlmarkdown'
cask 'rectangle'
# cask 'spotify'
cask 'visual-studio-code'
cask 'vivaldi'
# cask 'yubico-yubikey-manager'
cask 'zoom'

brew 'autoenv'
brew 'bash'
brew 'coreutils'
brew 'chruby'
brew 'exiftool'
brew 'ffmpeg'
brew 'git'
brew 'git-lfs'
brew 'gh'
brew 'micromamba'
brew 'python@3.11'
brew 'ruby-install'
brew 'saulpw/vd/visidata'
brew 'tmux'
# brew 'ykman'
brew 'yt-dlp'

# disable bluetooth on sleep
brew 'sleepwatcher'
brew 'blueutil'
