#!/bin/bash

echo "Install Homebrew packages"
brew update
brew tap Homebrew/bundle
brew bundle

mkdir ~/.bin
pushd ~/.bin

curl -fsSL https://recs.pl > recs
chmod +x recs

git clone https://github.com/Tarrasch/zsh-autoenv zsh-autoenv

popd
