#!/bin/bash
#
# inspiration:
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos
# https://macos-defaults.com/
# to read existing defaults domains:
# https://apple.stackexchange.com/a/198336

name="$1"

echo "Setting system preferences"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until this script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

sudo scutil --set ComputerName $name && \
sudo scutil --set HostName $name && \
sudo scutil --set LocalHostName $name && \
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $name

# Disable the sound effects on boot
sudo nvram StartupMute=%01

# Turn off Alert volume
defaults write NSGlobalDomain com.apple.sound.beep.volume -float 0

# Reduce transparency
# Requires Full Disk Access for calling application
defaults write com.apple.universalaccess reduceTransparency 1

# Menu bar: always show date and seconds
defaults write com.apple.menuextra.clock "ShowDate" -int 1
defaults write com.apple.menuextra.clock "ShowSeconds" -bool true

# Menu bar: show Bluetooth
defaults write com.apple.controlcenter "NSStatusItem Visible Bluetooth" -bool true
defaults -currentHost write com.apple.controlcenter "Bluetooth" -int 2

# Set highlight color to purple
# defaults write NSGlobalDomain AppleHighlightColor -string '0.835 0.871 0.897'

# Set sidebar icon size to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Always show scrollbars
# defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Display ASCII control characters using caret notation in standard text views
# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
# defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

# Disable Resume system-wide
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

# Disable automatic termination of inactive apps
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# Disable the crash reporter
# defaults write com.apple.CrashReporter DialogType -string "none"

# Set Help Viewer windows to non-floating mode
defaults write com.apple.helpviewer DevMode -bool true

# Reveal IP address, hostname, OS version, etc. when clicking the clock
# in the login window
# sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Restart automatically if the computer freezes
# systemsetup -setrestartfreeze on

# Never go into computer sleep mode
# systemsetup -setcomputersleep Off > /dev/null

# Disable AirPlay Receiver to free up ports 5000 and 7000
defaults -currentHost write com.apple.controlcenter AirplayRecieverEnabled -bool false

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Trackpad: swipe between pages with three fingers
defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerHorizSwipeGesture -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 1

# Trackpad: set click to light
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0

# Trackpad: enable silent clicking
defaults write com.apple.AppleMultitouchTrackpad ActuationStrength -int 0

# Enable “natural” (Lion-style) scrolling
# defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true

# trackpad cursor speed
defaults write NSGlobalDomain com.apple.trackpad.scaling -int 2

# Trackpad: use dragging option - three finger drag
defaults write com.apple.AppleMultitouchTrackpad DragLock -bool false
defaults write com.apple.AppleMultitouchTrackpad Dragging -bool false
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerDragGesture -bool true

# Trackpad: enable Mission Control gesture
defaults write com.apple.dock showMissionControlGestureEnabled -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.fourFingerVertSwipeGesture -int 2

# stop all those damn noises
defaults write NSGlobalDomain com.apple.sound.beep.feedback -bool false

# Increase sound quality for Bluetooth headphones/headsets
# defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
# ^ I think that's outdated. See below.
# https://www.macrumors.com/how-to/enable-aptx-aac-bluetooth-audio-codecs-macos/
defaults write bluetoothaudiod "Enable AptX codec" -bool true

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a fast keyboard repeat rate
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 2

# Automatically illuminate built-in MacBook keyboard in low light
# defaults write com.apple.BezelServices kDim -bool true
# Turn off keyboard illumination when computer is not used for 5 minutes
# defaults write com.apple.BezelServices kDimTime -int 300

# Disable automatic capitalization
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Press globe to do nothing
defaults write com.apple.HIToolbox AppleFnUsageType -int 0

# Use macOS control keys over function keys
defaults write -g com.apple.keyboard.fnState -bool false

# Enable keyboard shortcut for cycling through input sources
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 60 "{enabled = 1; value = { parameters = (32, 49, 262144); type = 'standard'; }; }"

# Prevent CMD+I from opening mail app
# <https://apple.stackexchange.com/a/108129>
# TODO: check that this works
defaults write com.apple.Safari NSUserKeyEquivalents -dict-add 'Email Link to This Page' '\0' 'Email This Page' '\0'

# Disable Universal Control
defaults write com.apple.universalcontrol Disable -bool true
defaults write com.apple.universalcontrol DisableMagicEdges -bool true

# Allow tab key to move focus between dialog buttons (requires logout)
defaults write -g AppleKeyboardUIMode -int 2

###############################################################################
# Screen                                                                      #
###############################################################################

# Disable screen saver
defaults write com.apple.screensaver idleTime -int 0
defaults write com.apple.screensaver lastDelayTime -int 1200

## Picture-in-Picture Zoom

# Enable zoom with scroll
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true

# Picture-in-Picture zoom style
defaults write com.apple.universalaccess closeViewZoomMode -int 1

# Zoomed image moves to keep pointer centered
defaults write com.apple.universalaccess closeViewPanningMode -int 2

# Don't smooth images
defaults write com.apple.universalaccess closeViewSmoothImages -bool false

# Toggle zoom with ctrl+option
defaults write com.apple.universalaccess closeViewPressOnReleaseOff -bool false

###############################################################################
# Energy                                                                      #
###############################################################################

# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400

# on battery
sudo pmset -b sleep 20 disksleep 15 displaysleep 3 halfdim 1 powernap 0 tcpkeepalive 0

# on power adapter
sudo pmset -c sleep 0 disksleep 15 displaysleep 30 halfdim 1 powernap 0

###############################################################################
# Finder                                                                      #
###############################################################################

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathBar -bool true

# Finder: allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# Set Default Finder Location to Home Folder
defaults write com.apple.finder NewWindowTarget -string "PfHm"

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Reduce the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0.25

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# Use column view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Enable AirDrop over Ethernet and on unsupported Macs running Lion
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Open folders in new windows instead of tabs
defaults write com.apple.finder FinderSpawnTab -bool false

# Remove tag favorites
defaults write com.apple.finder FavoriteTagNames -array

# Remove tags from sidebar
defaults write com.apple.finder ShowRecentTags -bool false

# Don't do anything when clicking the wallpaper
defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false

# Remove margins from tiled windows
defaults write com.apple.WindowManager EnableTiledWindowMargins -bool false

# Set VSCode as default app for opening text-related files
# <https://www.darraghoriordan.com/2021/09/15/vscode-default-text-files-mac>
duti -s com.microsoft.VSCode public.json all
duti -s com.microsoft.VSCode public.plain-text all
duti -s com.microsoft.VSCode public.python-script all
duti -s com.microsoft.VSCode public.shell-script all
duti -s com.microsoft.VSCode public.source-code all
duti -s com.microsoft.VSCode public.text all
duti -s com.microsoft.VSCode public.unix-executable all
# this works for files without a filename extension
duti -s com.microsoft.VSCode public.data all

duti -s com.microsoft.VSCode .c all
duti -s com.microsoft.VSCode .cfg all
duti -s com.microsoft.VSCode .conf all
duti -s com.microsoft.VSCode .cpp all
duti -s com.microsoft.VSCode .cs all
duti -s com.microsoft.VSCode .css all
duti -s com.microsoft.VSCode .csv all
duti -s com.microsoft.VSCode .go all
duti -s com.microsoft.VSCode .java all
duti -s com.microsoft.VSCode .js all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .jsx all
duti -s com.microsoft.VSCode .less all
duti -s com.microsoft.VSCode .log all
duti -s com.microsoft.VSCode .lua all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .pl all
duti -s com.microsoft.VSCode .py all
duti -s com.microsoft.VSCode .rb all
duti -s com.microsoft.VSCode .sass all
duti -s com.microsoft.VSCode .scss all
duti -s com.microsoft.VSCode .toml all
duti -s com.microsoft.VSCode .ts all
duti -s com.microsoft.VSCode .tsv all
duti -s com.microsoft.VSCode .tsx all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .vue all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yml all

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# Set dock to right hand side
# defaults write com.apple.dock orientation -string "right"

# Set the icon size of Dock items
defaults write com.apple.dock tilesize -int 57  # pixels

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Group windows by application in Mission Control
# defaults write com.apple.dock expose-group-by-app -bool true

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Speed up the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0.5

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Don't show recent apps in Dock
defaults write com.apple.dock show-recents -bool false

# Minimize windows using Scale Effect
defaults write com.apple.dock mineffect -string scale

# Minimize windows into application icon
defaults write com.apple.dock minimize-to-application -bool true

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# Top right screen corner → Put display to sleep
# Modifiers represent any keys to be pressed to trigger hot corner.
# 0: no modifier key
# 2^17 or 131072: shift
# 2^18 or 262144: control
# 2^19 or 524288: option
# 2^20 or 1048576: command
defaults write com.apple.dock wvous-tr-corner -int 10
defaults write com.apple.dock wvous-tr-modifier -int 0

# Remove bottom right default of Quick Note
defaults write com.apple.dock wvous-br-corner -int 0

###############################################################################
# Time Machine                                                                #
###############################################################################

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

###############################################################################
# Mac App Store                                                               #
###############################################################################

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

###############################################################################
# Screen Shots                                                                #
###############################################################################

# Disable shadow on screen shots
defaults write com.apple.screencapture disable-shadow -bool true

# Custom file prefix
# https://apple.stackexchange.com/q/245771
defaults write com.apple.screencapture name "Screenshot"

# Save screen shots to downloads
defaults write com.apple.screencapture location "~/Downloads"

###############################################################################
# Spotlight                                                                   #
###############################################################################

# Disable spotlight on external volumes
sudo defaults write /Library/Preferences/com.apple.SpotlightServer.plist ExternalVolumesIgnore -bool True

# This doesn't currently work. It breaks the Settings UI in macOS Sonoma.
# defaults write com.apple.Spotlight orderedItems -array \
# 	'{"enabled" = 1;"name" = "APPLICATIONS";}' \
# 	'{"enabled" = 1;"name" = "MENU_EXPRESSION";}' \
# 	'{"enabled" = 1;"name" = "CONTACT";}' \
# 	'{"enabled" = 1;"name" = "MENU_CONVERSION";}' \
# 	'{"enabled" = 1;"name" = "MENU_DEFINITION";}' \
# 	'{"enabled" = 1;"name" = "DOCUMENTS";}' \
# 	'{"enabled" = 1;"name" = "EVENT_TODO";}' \
# 	'{"enabled" = 1;"name" = "DIRECTORIES";}' \
# 	'{"enabled" = 1;"name" = "FONTS";}' \
# 	'{"enabled" = 1;"name" = "IMAGES";}' \
# 	'{"enabled" = 0;"name" = "MESSAGES";}' \
# 	'{"enabled" = 1;"name" = "MOVIES";}' \
# 	'{"enabled" = 1;"name" = "MUSIC";}' \
# 	'{"enabled" = 1;"name" = "MENU_OTHER";}' \
# 	'{"enabled" = 1;"name" = "PDF";}' \
# 	'{"enabled" = 1;"name" = "PRESENTATIONS";}' \
# 	'{"enabled" = 1;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}' \
# 	'{"enabled" = 1;"name" = "SPREADSHEETS";}' \
# 	'{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
# 	'{"enabled" = 0;"name" = "TIPS";}' \
# 	'{"enabled" = 1;"name" = "BOOKMARKS";}'

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Address Book" "Calendar" "Contacts" "Dashboard" "Dock" "Finder" "SystemUIServer"; do
	killall "$app" > /dev/null 2>&1
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
